### ISSUE TITLE
Convert to mixin

### ISSUE THREAD

**Issue by floscr** [jonsuh/hamburgers#24]
Hey,

This is not an issue, more a recommendation or a note :)

I've turned your sass code into a single mixin, which is easy to include and customize:

``` scss
@mixin burger($options: ()) {

  // Default settings
  // To customize just pass in the arguments in a map
  // Example:
  // @include burger((padding: 30px))
  $config: map-merge((
    padding: 15px,
    width: 40px,
    height: 4px,
    spacing: 6px,
    color: black,
    border-radius: 4px,
    hover-opacity: 0.7,
    background-color: black,
    hover-transition-duration: 0.15s,
    hover-transition-timing-function:  linear,
  ), $options);

  // Get the map properties and asign them to variables for improved readabilty
  $padding: map-get($config, padding);
  $width: map-get($config, width);
  $height: map-get($config, height);
  $spacing: map-get($config, spacing);
  $color: map-get($config, color);
  $border-radius: map-get($config, border-radius);
  $hover-opacity: map-get($config, hover-opacity);
  $background-color: map-get($config, background-color);
  $hover-transition-duration: map-get($config, hover-transition-duration);
  $hover-transition-timing-function: map-get($config, hover-transition-timing-function);

  // Styles
  // --------------------------------------------------------------------------

  padding: $padding;
  background-color: $background-color;

  &:hover {
    opacity: $hover-opacity;
  }

  .hamburger__container {
    width: $width;
    height: $height * 3 + $spacing * 2;
  }

  .hamburger__inner {
    transition: opacity $hover-transition-duration $hover-transition-timing-function;
    margin-top: $height/ -2;
    &,
    &::before,
    &::after {
      width: $width;
      height: $height;
      background-color: $background-color;
      border-radius: $border-radius;
    }

    &::before {
      top: ($spacing + $height) * -1;
    }

    &::after {
      bottom: ($spacing + $height) * -1;
    }
  }

}

.hamburger {
  display: inline-block;
  cursor: pointer;
}

// Undo button styles
button.hamburger {
  appearance: none;
  background-color: transparent;
  border: 0;
  margin: 0;
  overflow: visible;
}

.hamburger__container {
  display: inline-block;
  position: relative;
}

.hamburger__inner {
  display: block;
  top: 50%;

  &,
  &::before,
  &::after {
    position: absolute;
    transition-property: transform;
    transition-duration: 0.15s;
    transition-timing-function: ease;
  }

  &::before,
  &::after {
    content: '';
    display: block;
  }
}
```

This way you include the burger like this:

``` scss
.my-class {
  @include burger(( height: 30px ));
}
```

Multiple animations then could be included with an if/else block.
