### ISSUE TITLE
Best way to define different hamburger line lengths?

### ISSUE THREAD

**Issue by beourmuse** [jonsuh/hamburgers#49]
So I get this result?

<img width="53" alt="screen shot 2017-11-21 at 4 24 00 pm" src="https://user-images.githubusercontent.com/7823614/33053440-6e4df676-ced8-11e7-960d-5289c3d91012.png">

Thanks

**Comment by jonsuh** [comment]
@beourmuse The classes to target each layer is:
```css
.hamburger-inner { width: #px }
.hamburger-inner::before { width: #px }
.hamburger-inner::after { width: #px }
```

Keep in mind that based on the animated variant, selectors for the top, middle, and bottom layer varies—you would have to experiment. You’d also have to adjust the positioning of the layers (`right: X`)

Here’s an example:
```css
.hamburger-inner,
.hamburger-inner::before,
.hamburger-inner::after {
  right: 0;
}

.hamburger-inner {
  width: 20px;
}

.hamburger-inner::after {
  width: 30px;
}
```

Results in this for the `hamburger--3dx` variant:
![image](https://user-images.githubusercontent.com/359871/34084773-a8cdf0d0-e34b-11e7-81a9-c1b81caa81e4.png)

And as a note, if you plan on using any of the existing animations, the example breaks all animations, so you would further adapt the CSS for the animated state targeting the `.is-active` class.
