### ISSUE TITLE
Controlling color without SCSS

### ISSUE THREAD

**Issue by DannyBen** [jonsuh/hamburgers#53]
Trying to see what is the easiest, most future-compatible way to control colors in a non-SCSS setup.

Is this the way to go?

```css
.hamburger .hamburger-inner, .hamburger .hamburger-inner:after, .hamburger .hamburger-inner:before {
  background-color: #666;
}
```

If so, can I suggest maybe adding another class to these elements that will allow something like:

```css
.hamburger-icon { background-color: #666; }
```

**Comment by jonsuh** [comment]
@DannyBen The way to control the hamburger color with CSS is as follows:
```css
.hamburger-inner,
.hamburger-inner::before,
.hamburger-inner::after {
  background-color: red;
}
```

Unfortunately one class like `.hamburger-icon` wouldn’t work because of the pseudo classes (e.g. `::before` and `::after`)
