### ISSUE TITLE
Show a plus icon instead of nav icon

### ISSUE THREAD

**Issue by kamov** [jonsuh/hamburgers#58]
There is something existing that allow to change default nav icon to plus icon?

**Comment by kamov** [comment]
This seem work fine:

```css


.hamburger {

    .hamburger-inner {
      transform: rotate(0deg);
      &:after {
        bottom: 0;
        transform: rotate(-90deg);
      }
      &:before {
        top: 0;
      }
    }

  &.is-active {
    .hamburger-inner {
      transform: rotate(225deg);
      &:after {
        bottom: 0;
        transform: rotate(-90deg);
      }
    }
  }
}

```
